apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-service
  namespace: microservices-live-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversion-service
  template:
    metadata:
      labels:
        app: conversion-service
    spec:
      containers:
        - name: conversion-service
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:8100"
            - "-text={\"service\":\"conversion-service\",\"message\":\"Hello from Kubernetes conversion service\"}"
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: conversion-service
  namespace: microservices-live-demo
spec:
  selector:
    app: conversion-service
  ports:
    - port: 8100
      targetPort: 8100
