services:
  mysql:
    image: mysql:8.0
    container_name: compose-demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_db
    ports:
      - "3306:3306"

  compose-demo-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: compose-demo-service
    ports:
      - "8204:8204"
    environment:
      SERVER_PORT: 8204
    depends_on:
      - mysql
