events {}

http {
    server {
        listen 8765;

        location /exchange {
            proxy_pass http://currency-exchange-service:8000/;
        }

        location /conversion {
            proxy_pass http://currency-conversion-service:8100/;
        }

        location /eureka {
            proxy_pass http://eureka:8761/;
        }
    }
}
